### ISSUE TITLE
FEATURE / Micro 3D

### ISSUE THREAD

**Issue by Trujillo94** [SwanLab/Swan#106]
Steps:

- [ ] test FEM micro 3D: periodic BC. (Micro full, Chomog = C)

- [ ] Solve Chomog_AlphaBeta with alpha = [1 0 0 0 0 0] (from sphere to laminates)

- [ ] Negative Poisson 3D.

**Comment by Trujillo94** [comment]
Steps:

- [ ] test FEM micro 3D periodic BC,

**Comment by Trujillo94** [comment]
These ShapeFunctions died with the new Settings format, because they are not in the tests. Must revive eventually:

![image](https://user-images.githubusercontent.com/32714352/57783725-ed015800-772e-11e9-8fd7-7b3d83230c5e.png)

**Comment by tcreusc** [comment]
It's been a long time, but this is now included
