### ISSUE TITLE
Refactoring MeshUnfitted

### ISSUE THREAD

**Issue by Trujillo94** [SwanLab/Swan#115]
- [x] Integrator can integrate non unfitted meshes.
- [x] Robin mesh no longer Unfitted.
- [x] DesignVar's mesh --> composite.
- [ ] DiffReact using Integrator for M & K.
- [ ] Remove globalConnectivities from Mesh_Unfitted_Composite.
- [ ] Group Integration Params.
- [ ] Mesh_Unfitted_Single main props (when Interior): meshCut, meshFull = meshBackground(fullCells), meshBackground. + coord & connec (being arrays of cut and full's coords & connecs, or unified if feasible).
- [ ] Mesh_Unfitted_Single main props (when Boundary): similar but without meshFull.

**Comment by Trujillo94** [comment]
- [ ] Turn Builders into different settings

**Comment by tcreusc** [comment]
It's been a long time, but it seems like everything was fixed :)
