### ISSUE TITLE
How to study the code? To a new here

### ISSUE THREAD

**Issue by Rememberflower** [SwanLab/Swan#181]
I will appreciate it if your team can provide me a helper documention

**Comment by tcreusc** [comment]
Hi, thanks for checking out Swan! Unfortunately, we still do not have a first release -- the code is usable but somewhat chaotic. We hope to have a solid sprint to solve these issues in the upcoming months, and publish a guide when all of that is done. I'll try to ping you once we have it.

**Comment by joetristano** [comment]
Hello, any updates here?  Would love to be able to try this out but I cannot find any problems that work...

Thanks

**Comment by FerrerFerreAlex** [comment]
Hi, not yet, it is still in progress, our intention is to have something useful in the following months. Keep you informed!

**Comment by tcreusc** [comment]
> Hello, any updates here? Would love to be able to try this out but I cannot find any problems that work...
> 
> Thanks

Hey @joetristano, we now have some tutorials in the code. Feel free to ask any questions you may have
