### ISSUE TITLE
Octave compatible?

### ISSUE THREAD

**Issue by stefano2734** [SwanLab/Swan#186]
Compatible to free matlab clone octave?
No license is needed for octave.

If yes, please extend your info.
if unknown, untested with octave is also nice.
if no, it is also ok. Some commands are not compatible in octave.

So you are the expert. Perhaps you can make a fast test run.
Here some last infos about octave.
https://wiki.octave.org/Differences_between_Octave_and_Matlab
https://wiki.octave.org/Release_History
https://octave.org/NEWS-7.html

**Comment by tcreusc** [comment]
We really don't know, but we use a lot of different toolboxes from Matlab so it may be complicated.
