### ISSUE TITLE
Create Top Opt tutorial

### ISSUE THREAD

**Issue by FerrerFerreAlex** [SwanLab/Swan#263]
Something like: 
Mesh, LevelSet, Density (designVariable), PhysicalProblem, Shape Functionals, Cost, Constraint, Optimizer i solve..

**Comment by ZHOUJIAXIN0814** [comment]
Dear developers,

Thank you for sharing the toolbox.
I am learning topology optimization with matlab.
This is going to be very useful for me.

The tutorial in your website is a little difficult to understand for beginers.
It would be appreciated if you can update the tutorial.

Thank you very much.

Best regards

**Comment by FerrerFerreAlex** [comment]
Thanks for your words. This is our intention, we will let you know.
