### ISSUE TITLE
Create Tetra and Hexa from Matlab

### ISSUE THREAD

**Issue by FerrerFerreAlex** [SwanLab/Swan#267]
Extend UnitQuad to UnitCube with tetrahedra and Hexahedra. 
This is very useful.

**Comment by tcreusc** [comment]
Done! See commits dd377f2c796f9067ec0aa2b438db9ad1a41871e1, 926e092fa83bacbbf60bf02ee0894b9656f00b39. Currently in the mesh-refactoring branch
