### ISSUE TITLE
problem in Tutorial03_LevelSet

### ISSUE THREAD

**Issue by thepureB** [SwanLab/Swan#355]
<img width="1349" alt="屏幕截图 2024-05-31 091252" src="https://github.com/SwanLab/Swan/assets/16591884/ce331659-9e79-4a8b-9401-2f229337d702">

**Comment by tcreusc** [comment]
Hi, thanks for reporting this bug and sorry for the delay. I've solved this bug, if you update the code, everything should be working fine. Feel free to contact us again if you have any other questions
