### ISSUE TITLE
How to run the topology optimization in Matlab?

### ISSUE THREAD

**Issue by HeroWolffy** [SwanLab/Swan#361]
Dear SwanLab:
I'd like to learn the use of Swan for topology optimization, how to achieve the topology optimization in Matlab? Is there any guide?

**Comment by tcreusc** [comment]
Hello there @HeroWolffy! The repository includes a folder with tutorials showing how to run our topology optimization codes. See, for instance, ```TopOptTestTutorial.m```. If you have any other questions, feel free to contact with us again
