### ISSUE TITLE
Create Constant Function

### ISSUE THREAD

**Issue by tcreusc** [SwanLab/Swan#380]
**Current status**: we have to do something like `AnalyticalFunction.create(@(x) E*ones(size(squeeze(x(1,:,:)))), 2, obj.mesh);` and it's impractical

**Main classes/functions**: ConstantFunction, AnalyticalFunction

**Outline of the solution**
- [ ] Step 1
- [ ] ...

----
*Assigned to:* @gervilquin 
*Wingman:* @jose-antonio-torres

**Comment by gervilquin** [comment]
Small change in ndimf (as a function of constant input size) has been performed in commit 39aa1b65a721a5a2988a4157e0d3248d1e9a4c65

**Comment by gervilquin** [comment]
ConstantFunction NOT as a subtype of AnalyticalFunction d59c92a41bd9e8c7e82bb28d7c3865f85302a21a
