### ISSUE TITLE
DesignPatterns

### ISSUE THREAD

**Issue by FerrerFerreAlex** [SwanLab/Swan#70]

**Comment by FerrerFerreAlex** [comment]
**Abstract Factory File**
[AbstractFactory.pdf](https://github.com/FerrerFerreAlex/FEM-MAT-OO/files/2573565/AbstractFactory.pdf)

**Comment by Trujillo94** [comment]
[Design patterns - Composite.pdf](https://github.com/FerrerFerreAlex/FEM-MAT-OO/files/2596990/Design.patterns.-.Composite.pdf)

**Comment by marcnunezc** [comment]
[Strategy.pdf](https://github.com/FerrerFerreAlex/FEM-MAT-OO/files/2617108/Strategy.pdf)

**Comment by Trujillo94** [comment]
[Decorator.pdf](https://github.com/FerrerFerreAlex/FEM-MAT-OO/files/2664630/Decorator.pdf)

**Comment by FerrerFerreAlex** [comment]
[Builder.pdf](https://github.com/FerrerFerreAlex/FEM-MAT-OO/files/2715485/Builder.pdf)

**Comment by marcnunezc** [comment]
[Design patterns-command.pdf](https://github.com/FerrerFerreAlex/FEM-MAT-OO/files/2754718/Design.patterns-command.pdf)

**Comment by marcnunezc** [comment]
[Singleton.pdf](https://github.com/FerrerFerreAlex/FEM-MAT-OO/files/2804846/Singleton.pdf)

**Comment by Trujillo94** [comment]
[Null Object.pdf](https://github.com/FerrerFerreAlex/FEM-MAT-OO/files/2804872/Null.Object.pdf)

**Comment by marcnunezc** [comment]
[Mediator.pdf](https://github.com/SwanLab/Swan/files/3466913/Mediator.pdf)

**Comment by marcnunezc** [comment]
[Template Method.pdf](https://github.com/SwanLab/Swan/files/3468450/Template.Method.pdf)

**Comment by FerrerFerreAlex** [comment]
[Iterator.pdf](https://github.com/SwanLab/Swan/files/3468479/Iterator.pdf)

**Comment by Trujillo94** [comment]
[Design patterns - Observer.pdf](https://github.com/SwanLab/Swan/files/3493578/Design.patterns.-.Observer.pdf)

**Comment by FerrerFerreAlex** [comment]
[Structural, Functional, OO programming.pdf](https://github.com/SwanLab/Swan/files/3526763/Structural.Functional.OO.programming.pdf)

**Comment by marcnunezc** [comment]
[Deep learning Session 1](https://github.com/SwanLab/Swan/files/3551478/Deep.learning.-.session.1.pdf)

**Comment by Trujillo94** [comment]
[Design patterns - State.pdf](https://github.com/SwanLab/Swan/files/3579350/Design.patterns.-.State.pdf)

**Comment by Trujillo94** [comment]
[Design patterns - Private Data Class.pdf](https://github.com/SwanLab/Swan/files/3580751/Design.patterns.-.Private.Data.Class.pdf)
