### ISSUE TITLE
Renaming Project

### ISSUE THREAD

**Issue by Trujillo94** [SwanLab/Swan#76]
FEM-MAT-OO outdated. New name suggestions?

**Comment by Trujillo94** [comment]
I would like you all to contribute in a list of adjectives that capture code's essence. I start:

- Agile
- Versatile
- Adaptative
- Easy-to-grow/expand
-

**Comment by Trujillo94** [comment]
Name proposals:
- TopOpt Hub
- TopOpt Lab
- TopLab

**Comment by Trujillo94** [comment]
Alex:
- OptLab
- LabTop
- Labgile

**Comment by marcnunezc** [comment]
Some more suggestions, focusing on full names that have some meaning:

## MYTHOLOGY ##
Minerva -> Roman goddess of wisdom
Fenix/Phoenix -> Reborn = concept of adaptability/versatility
Tot/Thot/Toth/Thoth -> Egyptian god of wisdom
Gaia -> Greek goddess, ancestral mother of all life, creational
Hermes -> Greek god of speed and commerce 

## FICTIONAL ##
Ditto -> Pokemon that can adapt any form
Doraemon -> Plenty of tools
Mazinger -> Famous robot

**Comment by marcnunezc** [comment]
Closing issue as Swan was chosen!
